version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    fpm:
        build:
            dockerfile: ./docker/Dockerfile
            context: .
        volumes:
            -  ./:/var/www/html
